#ifndef REQUEST_PARSING_STATE_HPP
#define REQUEST_PARSING_STATE_HPP

enum RequestState {
	START_REQUEST = 0,

	START_METHOD,
	START_URI,
	START_PROTOCOL,
	START_END,

	HEADER_NAME,
	HEADER_COLON,
	HEADER_SP_AFTER_COLON,
	HEADER_VALUE,
	HEADER_CR,
	HEADER_CRLF,
	HEADER_END,
	HEADER_CHECK,

	BODY_BEGIN,
	BODY_NONCHUNK,
	BODY_CHUNK_START,
	BODY_CHUNK_SIZE,
	BODY_CHUNK_SIZE_CRLF,
	BODY_CHUNK_EXTENSION,
	BODY_CHUNK_EXTENSION_NAME,
	BODY_CHUNK_EXTENSION_VALUE,
	BODY_CHUNK_DATA,
	BODY_CHUNK_LASTDATA,
	BODY_CHUNK_CRLF,
	BODY_CHUNK_TRAILER,
	BODY_CHUNK_TRAILER_NAME,
	BODY_CHUNK_TRAILER_VALUE,
	BODY_CHUNK_TRAILER_CRLF,
	BODY_CHUNK_EMPTYLINE,
	BODY_END,

	DONE
};

#endif
